
{% set name = "plasmaboundaries" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21fd323aaba978fa17efaa0cecf89fdbdf10ef5bee78d2fe7d2212a32a9439d5

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib
    - scipy
    - numpy
    - sympy

test:
  imports:
    - plasmaboundaries
  source_files:
    - tests/test_model.py
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: https://github.com/RemDelaporteMathurin/plasma-boundaries
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Determine plasma flux functions for various plasma parameters and plasma configurations.'

  description: |
    This code computes and plots analytical solutions of the Grad-Shafranov
    (GS) equation for studying plasma equilibrium, stability and transport in
    fusion reactors
  doc_url: https://github.com/RemDelaporteMathurin/plasma-boundaries
  dev_url: https://github.com/RemDelaporteMathurin/plasma-boundaries

extra:
  recipe-maintainers:
    - remdelaportemathurin
    - shimwell