{% set version = "0.6.7" %}

package:
  name: dagmc_h5m_file_inspector
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dagmc_h5m_file_inspector/dagmc_h5m_file_inspector-{{ version }}.tar.gz
  sha256: c4d95ea2eb537d969a47e6d95497d762fc7b8d46349143f3734ea5e95aa24644

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy

test:
  imports:
    - dagmc_h5m_file_inspector
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fusion-energy/dagmc_h5m_file_inspector
  summary: Extracts information from DAGMC h5m files including volumes number, material tags
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - shimwell
