
{% set name = "paramak" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e31e2884e48ff3979e746f55b612a2d00d7decb9d5fd79ef2fee67eeccabbf0d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - cadquery=2
    - matplotlib
    - numpy
    - plasmaboundaries
    - plotly
    - pillow
    - scipy
    - sympy
  run:
    - python
    - cadquery=2
    - matplotlib
    - numpy
    - plasmaboundaries
    - plotly
    - pillow
    - scipy
    - sympy

test:
  imports:
    - paramak

about:
  home: https://github.com/ukaea/paramak
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Create parametric 3D fusion reactor CAD models.'

  description: |
    The Paramak python package allows rapid production of 3D CAD models of fusion reactors.
    The purpose of the Paramak is to provide geometry for parametric studies.
    It is possible to use the created geometry in engineering and neutronics studies as the
    STP or STL files produced can be automatically converted to DAGMC compatable neutronics
    models or meshed and used in finite element analysis codes.
  doc_url: https://paramak.readthedocs.io/en/main/
  dev_url: https://github.com/ukaea/paramak

extra:
  recipe-maintainers:
    - Shimwell
